// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Gallery': string;
  'Jobs': string;
  'Matrix': string;
  'Stories': string;
  'completed-list': string;
  'control': string;
  'delete-task': string;
  'form': string;
  'form-container': string;
  'is-danger': string;
  'is-help': string;
  'multiform': string;
  'task-list': string;
}
declare const cssExports: CssExports;
export = cssExports;
